#include "ft_printf.h"
#include <stdio.h>

int	ft_printf(const char *str, ...);

int	main(void)
{
	int				len;
	int				lenorig;
	char			c_test;
	char			*s_test;
	int				d_test;
	unsigned int	u_test;
	unsigned int	x_test;
	unsigned int	X_test;
	void			*p_test;

	c_test = 0;
	s_test = "stringtest";
	d_test = INT_MIN;
	u_test = 0;
	x_test = 0;
	X_test = 0;
	p_test = "0";

	printf("ORIGINAL %%C:");
	printf("\n");
	lenorig = printf("%c", c_test);
	printf("\n");
	printf("FT_PRINTF %%C:");
	printf("\n");
	len = ft_printf("%c", c_test);
	printf("\n");
	printf("\norig len:%d", lenorig);
	printf("\n  my len:%d \n", len);
	printf("------------\n");
	printf("ORIGINAL %%S:");
	printf("\n");
	lenorig = printf("%s", s_test);
	printf("\n");
	printf("FT_PRINTF %%S:");
	printf("\n");
	len = ft_printf("%s", s_test);
	printf("\n");
	printf("\norig len:%d", lenorig);
	printf("\n  my len:%d \n", len);
	printf("------------\n");
	printf("ORIGINAL %%D:");
	printf("\n");
	lenorig = printf("%d", d_test);
	printf("\n");
	printf("FT_PRINTF %%D:");
	printf("\n");
	len = ft_printf("%d", d_test);
	printf("\n");
	printf("\norig len:%d", lenorig);
	printf("\n  my len:%d \n", len);
	printf("------------\n");
	printf("ORIGINAL %%U:");
	printf("\n");
	lenorig = printf("%u", u_test);
	printf("\n");
	printf("FT_PRINTF %%U:");
	printf("\n");
	len = ft_printf("%u", u_test);
	printf("\n");
	printf("\norig len:%d", lenorig);
	printf("\n  my len:%d \n", len);
	printf("------------\n");
	printf("ORIGINAL %%P:");
	printf("\n");
	lenorig = printf("%p", p_test);
	printf("\n");
	printf("FT_PRINTF %%P:");
	printf("\n");
	len = ft_printf("%p", p_test);
	printf("\n");
	printf("\norig len:%d", lenorig);
	printf("\n  my len:%d \n", len);
	printf("------------\n");
	printf("ORIGINAL %%x:");
	printf("\n");
	lenorig = printf("%x", x_test);
	printf("\n");
	printf("FT_PRINTF %%x:");
	printf("\n");
	len = ft_printf("%x", x_test);
	printf("\n");
	printf("\norig len:%d", lenorig);
	printf("\n  my len:%d \n", len);
	printf("------------\n");
	printf("ORIGINAL %%X:");
	printf("\n");
	lenorig = printf("%X", x_test);
	printf("\n");
	printf("FT_PRINTF %%X:");
	printf("\n");
	len = ft_printf("%X", x_test);
	printf("\n");
	printf("\norig len:%d", lenorig);
	printf("\n  my len:%d \n", len);
	printf("------------\n");
	printf("ORIGINAL %%:");
	printf("\n");
	lenorig = printf("%%");
	printf("\n");
	printf("FT_PRINTF %%:");
	printf("\n");
	len = ft_printf("%%");
	printf("\norig len:%d", lenorig);
	printf("\n  my len:%d \n", len);
}
